### PR TITLE
Updates notebooks

### PR DESCRIPTION
**Pull request by mortonjt**
Addresses #3 and #4 

Also realized that one of the files for Figure2.ipynb was not committed - adding that now.

### CODE REVIEW

**Comment by antgonza** [comment]
Figure1-4 now open - haven't ran them but at least they open; BTW perhaps worth adding autopep8 in the install instructions ... however, https://github.com/knightlab-analyses/reference-frames/blob/4b581681c64bb746b5d44af01e010b09fe79be41/ipynb/simulation-benchmark.ipynb still broken ...

**Comment by mortonjt** [comment]
ahhh - it looks like there were merge conflicts before in the notebook.  damn

ok, those are removed now.

**Comment by antgonza** [comment]
Errors so far:
- Figure3 / cell 8: Screen Shot 2019-04-24 at 8 57 43 AM
- Figure4 / cell 11: Screen Shot 2019-04-24 at 8 58 41 AM
- simulation-benchmark / cell 1 😞: Screen Shot 2019-04-24 at 9 05 55 AM

**Comment by mortonjt** [comment]
Figure 3 : I think you have a bad environment.  I've just updated the install instructions to clarify this
Figure 4: Basically is working -- just removed the save figure since the paths changed
simulation-benchmark: there were some leftover dependencies that should have been dropped.  Those are now gone.

**Comment by mortonjt** [comment]
@antgonza can we merge this in?

**Comment by antgonza** [comment]
Sure ...

**Comment by mortonjt** [comment]
Thanks!

**Pull request merged**
